package vasylts.blackjack.user.databaseworker.hibernateworker;
// Generated Oct 29, 2015 5:01:25 PM by Hibernate Tools 4.3.1



/**
 * Userwallet generated by hbm2java
 */
public class Userwallet  implements java.io.Serializable {


     private long id;
     private Double balance;

    public Userwallet() {
    }

	
    public Userwallet(long id) {
        this.id = id;
    }
    public Userwallet(long id, Double balance) {
       this.id = id;
       this.balance = balance;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }




}


